export const products = [
  {
    id: "p001",
    name: "Gold Solitaire Ring",
    category: "Ring",
    price: 24999,
    currency: "INR",
    image: "/images/ring-1.jpg",
    metal: ["Gold", "Rose Gold"],
    variants: ["Size 6", "Size 7", "Size 8"],
    description:
      "This solitaire ring features a clean, minimal design crafted for everyday elegance. The smooth band and centered stone create a timeless look suitable for both casual and formal occasions. Designed for comfort and durability, it pairs easily with other jewellery or stands strong on its own.",
    inStock: true,
  },
  {
    id: "p002",
    name: "Silver Heart Necklace",
    category: "Necklace",
    price: 8999,
    currency: "INR",
    image: "/images/necklace-1.jpg",
    metal: ["Silver"],
    variants: ["16 inch", "18 inch"],
    description:
      "A delicate heart-shaped pendant suspended on a fine silver chain. This necklace is lightweight and comfortable for all-day wear, making it ideal for gifting or personal use. The polished finish reflects light beautifully and complements both western and traditional outfits.",
    inStock: true,
  },
  {
    id: "p003",
    name: "Diamond Stud Earrings",
    category: "Earrings",
    price: 17999,
    currency: "INR",
    image: "/images/earrings-1.jpg",
    metal: ["Gold", "White Gold"],
    variants: ["3mm", "4mm"],
    description:
      "Classic diamond stud earrings designed for versatility and daily comfort. The secure setting ensures stability while maintaining a refined sparkle. Suitable for work, events, or casual wear, these studs are a staple addition to any jewellery collection.",
    inStock: false,
  },
  {
    id: "p004",
    name: "Pearl Charm Bracelet",
    category: "Bracelet",
    price: 11999,
    currency: "INR",
    image: "/images/bracelet-1.jpg",
    metal: ["Silver"],
    variants: ["Small", "Medium", "Large"],
    description:
      "This bracelet features softly polished pearls arranged with subtle spacing for a balanced look. Designed to feel light on the wrist, it adds understated elegance without overpowering the outfit. Ideal for festive wear, celebrations, or refined daily styling.",
    inStock: true,
  },
  {
    id: "p005",
    name: "Rose Gold Infinity Ring",
    category: "Ring",
    price: 15999,
    currency: "INR",
    image: "/images/ring-2.jpg",
    metal: ["Rose Gold"],
    variants: ["Size 6", "Size 7", "Size 8"],
    description:
      "An infinity-inspired ring symbolizing continuity and balance. Crafted in rose gold with smooth curves, it delivers a modern yet meaningful design. Comfortable for extended wear and suitable for stacking with other rings.",
    inStock: true,
  },
  {
    id: "p006",
    name: "Emerald Drop Earrings",
    category: "Earrings",
    price: 21999,
    currency: "INR",
    image: "/images/earrings-2.jpg",
    metal: ["Gold"],
    variants: ["Standard"],
    description:
      "Elegant drop earrings featuring emerald-toned stones set in a refined gold frame. Designed to create gentle movement and visual interest, these earrings elevate evening and festive outfits while remaining comfortable to wear.",
    inStock: true,
  },
  {
    id: "p007",
    name: "Minimal Gold Chain",
    category: "Necklace",
    price: 12999,
    currency: "INR",
    image: "/images/necklace-2.jpg",
    metal: ["Gold"],
    variants: ["18 inch", "20 inch"],
    description:
      "A simple gold chain designed for everyday layering or standalone wear. The lightweight construction ensures comfort while maintaining strength and durability. Works well with pendants or as a subtle accent on its own.",
    inStock: true,
  },
  {
    id: "p008",
    name: "Floral Stud Earrings",
    category: "Earrings",
    price: 6999,
    currency: "INR",
    image: "/images/earrings-3.jpg",
    metal: ["Silver"],
    variants: ["Standard"],
    description:
      "Floral-inspired stud earrings crafted with soft detailing and a polished silver finish. Designed to be lightweight and easy to wear, these studs add a playful yet elegant touch suitable for daily use.",
    inStock: true,
  },
  {
    id: "p009",
    name: "Gold Bangle Bracelet",
    category: "Bracelet",
    price: 28999,
    currency: "INR",
    image: "/images/bracelet-2.jpg",
    metal: ["Gold"],
    variants: ["Medium", "Large"],
    description:
      "A solid gold bangle with a smooth finish and structured form. Designed to hold its shape while remaining comfortable, this piece works well as a statement accessory or paired with multiple bangles.",
    inStock: true,
  },
  {
    id: "p010",
    name: "Moon Pendant Necklace",
    category: "Necklace",
    price: 9999,
    currency: "INR",
    image: "/images/necklace-3.jpg",
    metal: ["Silver"],
    variants: ["18 inch"],
    description:
      "A crescent moon pendant symbolizing calm and balance. Finished with a subtle shine, this necklace is designed for casual styling while still carrying visual character and meaning.",
    inStock: true,
  },
  {
    id: "p011",
    name: "Vintage Gold Ring",
    category: "Ring",
    price: 19999,
    currency: "INR",
    image: "/images/ring-3.jpg",
    metal: ["Gold"],
    variants: ["Size 7", "Size 8", "Size 9"],
    description:
      "Inspired by vintage jewellery aesthetics, this ring features engraved detailing and a heavier band. Built for durability and visual depth, it suits those who prefer classic designs with strong character.",
    inStock: false,
  },
  {
    id: "p012",
    name: "Charm Link Bracelet",
    category: "Bracelet",
    price: 13999,
    currency: "INR",
    image: "/images/bracelet-3.jpg",
    metal: ["Silver"],
    variants: ["Adjustable"],
    description:
      "A link-style bracelet featuring subtle charm elements for a playful yet refined look. The adjustable fit ensures comfort, making it suitable for long wear across different wrist sizes.",
    inStock: true,
  },
  {
    id: "p013",
    name: "Teardrop Pearl Earrings",
    category: "Earrings",
    price: 14999,
    currency: "INR",
    image: "/images/earrings-4.jpg",
    metal: ["Silver"],
    variants: ["Standard"],
    description:
      "Teardrop-shaped pearl earrings designed to create a soft, elegant silhouette. Ideal for formal occasions, these earrings balance sophistication with comfort and lightness.",
    inStock: true,
  },
  {
    id: "p014",
    name: "Layered Gold Necklace",
    category: "Necklace",
    price: 18999,
    currency: "INR",
    image: "/images/necklace-4.jpg",
    metal: ["Gold"],
    variants: ["18 inch"],
    description:
      "A layered necklace design that adds depth and texture without appearing heavy. Each chain is balanced in length to sit comfortably and enhance modern styling.",
    inStock: true,
  },
  {
    id: "p015",
    name: "Minimal Silver Ring",
    category: "Ring",
    price: 5999,
    currency: "INR",
    image: "/images/ring-4.jpg",
    metal: ["Silver"],
    variants: ["Size 6", "Size 7", "Size 8"],
    description:
      "A clean and understated silver ring designed for everyday use. Its smooth edges and lightweight build make it suitable for continuous wear without discomfort.",
    inStock: true,
  },
  {
    id: "p016",
    name: "Gold Hoop Earrings",
    category: "Earrings",
    price: 16999,
    currency: "INR",
    image: "/images/earrings-5.jpg",
    metal: ["Gold"],
    variants: ["Small", "Medium"],
    description:
      "Classic gold hoop earrings with a secure closure and balanced weight. Designed to be versatile, they pair easily with casual outfits as well as evening wear.",
    inStock: true,
  },
  {
    id: "p017",
    name: "Statement Cuff Bracelet",
    category: "Bracelet",
    price: 20999,
    currency: "INR",
    image: "/images/bracelet-4.jpg",
    metal: ["Silver"],
    variants: ["One Size"],
    description:
      "A bold cuff bracelet featuring a structured form and matte finish. Designed to stand out while remaining comfortable, it adds character to minimal outfits.",
    inStock: true,
  },
  {
    id: "p018",
    name: "Classic Mangalsutra",
    category: "Necklace",
    price: 32999,
    currency: "INR",
    image: "/images/necklace-5.jpg",
    metal: ["Gold"],
    variants: ["18 inch"],
    description:
      "A traditional mangalsutra design combining cultural significance with modern finishing. Crafted for durability and daily wear, it balances tradition and simplicity.",
    inStock: true,
  },
  {
    id: "p019",
    name: "Textured Gold Band",
    category: "Ring",
    price: 17999,
    currency: "INR",
    image: "/images/ring-5.jpg",
    metal: ["Gold"],
    variants: ["Size 7", "Size 8"],
    description:
      "A textured gold band designed with subtle surface detailing for added depth. The finish provides a distinctive look while maintaining a comfortable fit.",
    inStock: true,
  },
  {
    id: "p020",
    name: "Crystal Pendant Necklace",
    category: "Necklace",
    price: 10999,
    currency: "INR",
    image: "/images/necklace-6.jpg",
    metal: ["Silver"],
    variants: ["18 inch"],
    description:
      "A clear crystal pendant suspended on a fine silver chain. Designed to catch light subtly, this necklace works well for both daily wear and evening styling.",
    inStock: true,
  },
];
